/**
 * 
 */
package com.grouptwo.bookstore.repo;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.grouptwo.bookstore.dao.OrderRepository;
import com.grouptwo.bookstore.model.Book;
import com.grouptwo.bookstore.model.Order;

/**
 * @author HY1916H
 *
 */
@SpringBootTest
class OrderRepoTest {

	@Autowired
	private OrderRepository orderRepoTest;
	
	/**
	 * @throws java.lang.Exception
	 */
	@BeforeEach
	void setUp() throws Exception {
		System.out.println("Setting Up..!!");
	}

	@Test
	void isExistsByOrderId() {
		Order orderForTest = new Order(20, "Shipping", 3000);
		orderRepoTest.save(orderForTest);
		Order addedOrder = orderRepoTest.save(orderForTest);
		int orderIdAutoGenerated = addedOrder.getOrderId();
		
		Boolean actualResult = orderRepoTest.isExistsByOrderId(orderIdAutoGenerated);
		
		
		assertThat(actualResult).isTrue();
		
	}
	/**
	 * @throws java.lang.Exception
	 */
	@AfterEach
	void tearDown() throws Exception {
		System.out.println("Tearing Down");
		orderRepoTest.deleteAll();
	}

	

}
