/**
 * 
 */
package com.grouptwo.bookstore.repo;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.grouptwo.bookstore.dao.RatingRepository;
import com.grouptwo.bookstore.model.Book;
import com.grouptwo.bookstore.model.Rating;

/**
 * @author HY1916H
 *
 */
@SpringBootTest
class RatingRepoTest {

	@Autowired
	private RatingRepository ratingRepoTest;
	/**
	 * @throws java.lang.Exception
	 */
	@BeforeEach
	void setUp() throws Exception {
		System.out.println("Setting Up..!!");
	}

	@Test
	void isExistsByRatingId() {
		Rating ratingForTest = new Rating(20, 9);
		Rating addedRating = ratingRepoTest.save(ratingForTest);
		int ratingIdAutoGenerated = addedRating.getRatingId();
		
		Boolean actualResult = ratingRepoTest.isExistsByRatingId(ratingIdAutoGenerated);
		
		
		assertThat(actualResult).isTrue();
		
	}
	/**
	 * @throws java.lang.Exception
	 */
	@AfterEach
	void tearDown() throws Exception {
		System.out.println("Tearing Down");
		ratingRepoTest.deleteAll();
	}

}
