/**
 * 
 */
package com.grouptwo.bookstore.repo;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.grouptwo.bookstore.dao.UserRepository;
import com.grouptwo.bookstore.model.Book;
import com.grouptwo.bookstore.model.User;

/**
 * @author HY1916H
 *
 */
@SpringBootTest
class UserRepoTest {

	@Autowired
	private UserRepository userRepoTest;
	/**
	 * @throws java.lang.Exception
	 */
	@BeforeEach
	void setUp() throws Exception {
		System.out.println("Setting Up..!!");
	}

	@Test
	void isExistsByUserId() {
		User userForTest = new User(20, "John", "John@example.com", "John123", "New York", 965231);
		User addedUser = userRepoTest.save(userForTest);
		int userIdAutoGenerated = addedUser.getUserId();
		
		Boolean actualResult = userRepoTest.isExistsByUserId(userIdAutoGenerated);
		
		
		assertThat(actualResult).isTrue();
		
	}
	
	
	/**
	 * @throws java.lang.Exception
	 */
	@AfterEach
	void tearDown() throws Exception {
		System.out.println("Tearing Down");
		userRepoTest.deleteAll();
	}

}
